fixtures:
  base_dir: fpgen.example.fixtures.v1
  load:
    Unit:
      module: load_unit
      class: LoadUnit
      attributes:
        quantity: 20
        catalog: "/home/INTEXSOFT/filipp.zotov/PycharmProjects/FixturesPackGenerator/fpgen/example/fixtures/catalog/v1/unit_list.json"
        autoload: True
    Category:
      module: load_category
      class: LoadCategory
      attributes:
        quantity: 20
        autoload: True
    Goods:
      module: load_goods
      class: LoadGoods
      attributes:
        quantity: 1000
